fix: Use `globalThis` to reference html collections
Otherwise this causes errors in `node`

```
  1) SWI-Prolog WebAssembly on Node.js
       [node] should conform to certain typing:
     ReferenceError: HTMLCollection is not defined
      at /home/jesse/Documents/github/npm-swipl-wasm/dist/swipl/swipl.js:9:184617
      at module.exports (dist/swipl-node.js:8:10)
      at Context.<anonymous> (tests/node.js:14:27)
      at process.processImmediate (node:internal/timers:471:21)
```