PORT: 0005-plbuild.patch
If we are building with --host=mingw32 --build=mingw32 (i.e. we are
building with MinGW on a Windows machine) then we need to ensure that
swipl-ld-build.exe can be built:

gcc -DHOST_OS_WINDOWS \
                -DPLBASE="\"/c/git/pl-devel-test/src/..\"" \
                -I. -I. -g -O2 -o swipl-ld-build.exe ./swipl-ld.c
<snip>
c:\git\pl-devel\src/./swipl-ld.c:1552: undefined reference to `_xos_close'
c:\git\pl-devel\src/./swipl-ld.c:1520: undefined reference to `_xos_close'
c:\git\pl-devel\src/./swipl-ld.c:1521: undefined reference to `_xos_remove'

This patch adds a PLBUILD variable to the Makefile. If $PLBUILD ==
$PLARCH == *mingw* then we can build swipl-ld-build.exe with libuxnt.a